-- Seed data for testing
-- Note: This creates sample articles without user profiles since auth users need to be created through the auth system

-- Sample articles with placeholder author IDs (these will be updated when real users sign up)

-- Note: Since we can't create auth users directly, we'll skip the seed data for now
-- Users can sign up through the app and create their own content
-- This file is kept for reference and can be used later when we have real users

-- Example of how to insert articles (commented out):
/*
INSERT INTO articles (id, title, slug, content, excerpt, cover_image, author_id, published, featured, tags, reading_time, view_count, likes_count, comments_count, published_at) VALUES
('650e8400-e29b-41d4-a716-446655440000', 'The Future of Web Development: Trends to Watch in 2024', 'future-web-development-2024', '<h2>Introduction</h2><p>Web development is evolving at an unprecedented pace. As we move through 2024, several key trends are shaping the future of how we build and interact with web applications.</p><h2>1. AI-Powered Development Tools</h2><p>Artificial Intelligence is revolutionizing the development process. From code generation to automated testing, AI tools are becoming indispensable for modern developers.</p><h2>2. WebAssembly Adoption</h2><p>WebAssembly (WASM) is gaining traction as a way to run high-performance applications in the browser. This technology opens up new possibilities for web applications.</p><h2>3. Progressive Web Apps (PWAs)</h2><p>PWAs continue to bridge the gap between web and native applications, offering offline functionality and native-like experiences.</p><h2>Conclusion</h2><p>The future of web development is bright, with these technologies leading the charge toward more efficient, powerful, and user-friendly web experiences.</p>', 'Explore the cutting-edge trends shaping web development in 2024, from AI-powered tools to WebAssembly and Progressive Web Apps.', 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=400&fit=crop', '550e8400-e29b-41d4-a716-446655440000', true, true, ARRAY['web-development', 'technology', 'ai', 'webassembly', 'pwa'], 8, 1247, 89, 23, '2024-01-15 10:30:00+00'),

('650e8400-e29b-41d4-a716-446655440001', 'Content Marketing Strategies That Actually Work', 'content-marketing-strategies-2024', '<h2>Why Content Marketing Matters</h2><p>In today''s digital landscape, content marketing has become the cornerstone of successful business growth. But not all content strategies are created equal.</p><h2>1. Know Your Audience</h2><p>Understanding your target audience is crucial. Create detailed buyer personas and tailor your content to their specific needs and pain points.</p><h2>2. Consistency is Key</h2><p>Regular publishing schedules help build audience expectations and improve search engine rankings.</p><h2>3. Quality Over Quantity</h2><p>Focus on creating valuable, well-researched content rather than churning out mediocre posts.</p><h2>4. Leverage Multiple Formats</h2><p>Diversify your content with blog posts, videos, podcasts, infographics, and interactive content.</p><h2>Measuring Success</h2><p>Track key metrics like engagement rates, conversion rates, and organic traffic to measure the effectiveness of your content strategy.</p>', 'Discover proven content marketing strategies that drive real results for businesses in 2024. Learn how to create content that converts.', 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop', '550e8400-e29b-41d4-a716-446655440001', true, true, ARRAY['content-marketing', 'digital-marketing', 'strategy', 'business'], 6, 892, 67, 18, '2024-01-12 14:20:00+00'),

('650e8400-e29b-41d4-a716-446655440002', 'Building Scalable React Applications: Best Practices', 'scalable-react-applications-best-practices', '<h2>Introduction to Scalable React</h2><p>Building React applications that can grow with your business requires careful planning and adherence to best practices from the start.</p><h2>Component Architecture</h2><p>Design your components with reusability and maintainability in mind. Follow the single responsibility principle and create a clear component hierarchy.</p><h2>State Management</h2><p>Choose the right state management solution for your application size. Context API for smaller apps, Redux or Zustand for larger applications.</p><h2>Code Organization</h2><p>Implement a clear folder structure that scales with your team and project size. Group related files together and maintain consistent naming conventions.</p><h2>Performance Optimization</h2><p>Use React.memo, useMemo, and useCallback strategically. Implement code splitting and lazy loading for better performance.</p><h2>Testing Strategy</h2><p>Implement comprehensive testing with unit tests, integration tests, and end-to-end tests to ensure application reliability.</p>', 'Learn essential best practices for building React applications that scale efficiently with your business needs and team growth.', 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=400&fit=crop', '550e8400-e29b-41d4-a716-446655440002', true, false, ARRAY['react', 'javascript', 'frontend', 'scalability', 'best-practices'], 10, 1456, 112, 34, '2024-01-10 09:15:00+00'),

('650e8400-e29b-41d4-a716-446655440003', 'The Psychology of User Experience Design', 'psychology-user-experience-design', '<h2>Understanding User Psychology</h2><p>Great UX design goes beyond aesthetics—it''s about understanding how users think, feel, and behave when interacting with digital products.</p><h2>Cognitive Load Theory</h2><p>Minimize cognitive load by simplifying interfaces and reducing the number of decisions users need to make at any given time.</p><h2>The Power of Visual Hierarchy</h2><p>Use size, color, contrast, and spacing to guide users'' attention and create clear information hierarchies.</p><h2>Emotional Design</h2><p>Design for emotions by considering how your interface makes users feel. Positive emotions lead to better user experiences and increased engagement.</p><h2>Behavioral Patterns</h2><p>Leverage common behavioral patterns like the F-pattern for reading and the serial position effect for navigation design.</p><h2>Accessibility and Inclusion</h2><p>Design for all users by considering different abilities, contexts, and technological constraints.</p>', 'Explore how psychological principles can improve your UX design decisions and create more intuitive, user-friendly digital experiences.', 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=400&fit=crop', '550e8400-e29b-41d4-a716-446655440003', true, true, ARRAY['ux-design', 'psychology', 'user-experience', 'design-thinking'], 7, 743, 56, 15, '2024-01-08 16:45:00+00'),

('650e8400-e29b-41d4-a716-446655440004', 'Getting Started with TypeScript: A Comprehensive Guide', 'getting-started-typescript-guide', '<h2>Why TypeScript?</h2><p>TypeScript adds static type checking to JavaScript, helping developers catch errors early and write more maintainable code.</p><h2>Setting Up Your Environment</h2><p>Learn how to install TypeScript, configure your development environment, and set up your first TypeScript project.</p><h2>Basic Types and Interfaces</h2><p>Understand TypeScript''s type system, including primitive types, arrays, objects, and how to create custom interfaces.</p><h2>Functions and Classes</h2><p>Explore how TypeScript enhances JavaScript functions and classes with type annotations and access modifiers.</p><h2>Advanced Features</h2><p>Dive into generics, union types, intersection types, and other advanced TypeScript features that make your code more flexible and type-safe.</p><h2>Best Practices</h2><p>Learn TypeScript best practices for naming conventions, file organization, and gradual adoption in existing JavaScript projects.</p>', 'A beginner-friendly guide to TypeScript that covers everything you need to know to start writing type-safe JavaScript applications.', 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&h=400&fit=crop', '550e8400-e29b-41d4-a716-446655440002', true, false, ARRAY['typescript', 'javascript', 'programming', 'tutorial'], 12, 2134, 145, 42, '2024-01-05 11:30:00+00');
*/
